#!/bin/bash

set -o pipefail
set -e

# Global settings
SCRIPT=$(readlink -f "${0}")
DIR=$(dirname "${SCRIPT}")
cd "${DIR}" || exit 1

# Configure and activate the virtual environment
python3 -m venv env
. ./env/bin/activate
python3 -m pip install --upgrade pip

# Install from requirements, if present
if [ -f requirements.txt ] ; then
  python3 -m pip install -r ./requirements.txt
fi

# If bdast is already installed from requirements, then this won't
# change it, otherwise it will install the latest version
python3 -m pip install bdast

exec bdast run "$@"

exit 1

