---

name: push_branch_main
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  push_branch_main:
    name: "push_branch_main"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: push_branch_main
        shell: bash
        run: |
          ./entrypoint push_branch_main
        env:
          SECRET_REGISTRY_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

